### ISSUE TITLE
[Feature request] Win counter Like kof '95 and above.

### ISSUE THREAD

**Issue by IcDasNMs** [city41/kof94te#109]
Hello. is possible add an 'win count' like kof95 and above? I talk about the info above energy bar: _"Beat By xx"_. If player loses goes to 0 again. Is two adresses one for p1 wins and other for p2 wins.

Add this feature will turn possible play ranked matchs in fightcade2 and others clients that uses memory addresses to detect win.
Thanks.

**Comment by IcDasNMs** [comment]
![kof95-05-25-005852](https://github.com/city41/kof94te/assets/110349306/e8753124-569c-4c40-823c-c4227d4b4f9e)

**Comment by city41** [comment]
There's been several feature requests like this, all to make versus play a bit nicer. I'm not against them, but I also don't think they fit into this hack. Truthfully random select didn't either, but I added it anyway.

I have no plans to add features like this to the hack. But if anyone makes a hack like this, I'm happy to make sure it is compatible with kof94te so both hacks can be applied to the same rom.

**Comment by IcDasNMs** [comment]
Ok.
