### ISSUE TITLE
Select fighters order with buttons

### ISSUE THREAD

**Issue by Darthtallgeese** [city41/kof94te#115]
Like this

![kof95sp-240528-213713](https://github.com/city41/kof94te/assets/10185487/0d54030c-75c9-4e99-9e59-243bc5948b85)

Is it possible to add this feature?

**Comment by city41** [comment]
It's definitely possible but I don't plan to do it. I don't feel it fits into this hack. If anyone makes a patch that does this I'll make sure it's compatible with kof94te.

Someone in the discord has mentioned they plan to make this hack.
