### ISSUE TITLE
kof94 avatars

### ISSUE THREAD

**Issue by city41** [city41/kof94te#128]
Offer up the kof94 avatars as an option when building the rom

**Comment by dezraj** [comment]
Hello! I want to use the 1.3 beta version which has the KOF'94 avatars, but I'm not sure which patches version should I use, the a94 or a95 one.

Is "a94" for KOF'94 avatars and "a95" '95 ones? Are there any other bug fixes in this beta version?

Thank you so much for your great work.

**Comment by city41** [comment]
Yup, a94 is the kof94 avatars version.

You can also build the rom here

https://neorh-git-a94-matt-greers-projects.vercel.app/
