### ISSUE TITLE
bad call to renderCurFocusedCharName

### ISSUE THREAD

**Issue by zelurker** [city41/kof94te#133]
Hi !

I just added your patch to raine lately, see there : https://www.1emulation.com/forums/topic/37618-support-for-new-rom-hack-projects/#comments
and since the method to display sprites in raine is different from mame, there are some left over sprites on the winning screen, the exact description of the problem is in the thread linked above.
What happens is that instead of writing to the fix area it writes to $8200 + $132 in the video memory, which enables a column of sprites which should stay disabled. The problem actually appeared in your 1.1.9 version, and it's still here in 1.3.0b0.
I managed to identify the bogus call as it's said at the end of the thread, for the a94 patch it's at offset 0x1bd8ea in the rom (which is in the bank actually), and 0x1bd8ca for a95. Replace the word at this address by $4e75 (rts) to fix the problem.

For now I have added this patch to my git, but I report it here in the hope you'll fix it on your side...

**Comment by zelurker** [comment]
Actually error on the diagnostic and the fix ! What happens actually in your code is that you use :
move.b $#11,d0
loop:
move #$f20,$3c0002
dbra d0,loop
which looks very good at 1st look, except dbra works on words !!! Which means that you must use instead
move.w #$11,d0
and so the patch for your code becomes
0x1be018 -> 0x303c for a4 patch
0x1be018-0x20 -> 0x303c for a5 patch
the previous proposed solution removed the player name on the player selection screen which is obviously not a good solution !

**Comment by city41** [comment]
Awesome, thanks for the report and investigation. And doh, using bytes with dbra is a mistake I've made a few times 😬

I'm currently out of town, but I'll get this fixed up later this week when I get back.

**Comment by zelurker** [comment]
Cool, thanks ! :)

Le mar. 18 juin 2024 à 20:05, Matt Greer ***@***.***> a
écrit :

**Comment by city41** [comment]
Ok this is now fixed. The issue didn't happen on MAME or on real hardware, which is why I never noticed it. Thanks!

**Comment by city41** [comment]
This has now been released in 1.3.0

**Comment by zelurker** [comment]
Ok thanks, and thanks for the info, it means we should eventually consider
changing the way sprites are drawn... but since I never found any official
stuff which needed that to change, I'd like to avoid it if possible !

Le mer. 19 juin 2024 à 21:07, Matt Greer ***@***.***> a
écrit :

**Comment by city41** [comment]
Oh and also it seems like Kawaks had the same issue. As this fix also fixed up the same graphical glitching for it. So double thanks :)
