### ISSUE TITLE
Make the hack compatible with slow ROM

### ISSUE THREAD

**Issue by city41** [city41/kof94te#134]
The hack relies on the fact that in most environments, the game does not play using slow wait cycles. If you use proper wait cycles as the original KOF94 does, the character select screen will be very laggy.

Since the proper wait cycles are not used, there can be some graphical glitching in character sprites throughout gameplay. This is true on the MiSTer, and real hardware using a NeoSD. This issue does not manifest on software emulators as far as I can tell.

The MiSTer team provided a good insight

> The kof94te.neo file uses the same ID (0x55) as the original Kof94. The original cartridge uses slow ROM and so it has wait states enabled. If wait states are not used then there will be sprite glitches even on original hardware.
> 
> Your hack needs to run without wait states so a solution is to set a different ID in the .neo file

See if the character select screen can be improved to work with slow ROM. I believe the only way this can be tested is on the MiSTer. As far as I know, the NeoSD does not emulate slow ROM. But maybe it does?

**Comment by MrsBison** [comment]
Problem solved. New workaround is great.
Plays as regular 94 and also no garfik glitch in the character select screen.

Closeed

**Comment by city41** [comment]
@MrsBison  the workaround gets the hack working in its current state on mister. But it will show graphical glitches occassionally. They are very minor and don't happen often, you may not even notice them. They happen on real hardware too.

That is what this issue is about, not the lag the mister used to show.

**Comment by MrsBison** [comment]
Ahm but the controls working perfect ? I tested it a few mins ago.
Last time i wanst able to play ....

**Comment by city41** [comment]
This work is being done on the [slowRom](https://github.com/city41/kof94te/tree/slowRom) branch.

**Comment by city41** [comment]
Here is the glitch, this happens on the MiSTer and likely real hardware too. This is what I'm trying to fix


https://github.com/city41/kof94te/assets/141159/2d7ff564-b1f2-4774-b189-a55c8029d6da

**Comment by city41** [comment]
I posted this on the Neo forum. Adding here too in case anyone knows about this

A game cartridge can tell the system to add in some wait cycles when moving data around by setting 5 volts on some of the cartridge pins.

This is mostly used to slow down video RAM writes, as writing to video RAM too quickly causes issues. KOF94 is one game that does this.

Emulators, the MiSTer (until fairly recently), and I believe the NeoSD, ignore this wait cycle setting. And so I barreled ahead and built the whole ROM hack without taking it into account :( I had no idea, but hey, live and learn.

So KOF94TE does not turn on the wait cycle setting, which causes graphical glitches like this (watch Chang in comment just above this one)

That is at 5% of full speed, the glitch is so fast you usually miss it.

Thankfully it's rare, it took me a long time to catch this one, and no one has ever reported this. But it's still there and I'd like to fix it. Unfortunately the fix won't be easy, so I might give up and just live with this.

This is why the hack was so laggy on the MiSTer. With the wait cycles turned on, the hack asks the cpu to do too much. The wait cycles are basically "underclocking" the cpu.

**This never happens on emulators, so if you are playing that way, you're good.**

## Wait cycles on NeoSD?

Does anyone know if the NeoSD supports the wait cycle setting? I asked on their discord but so far no answer. When playing vanilla KOF94 or KOF94TE on a NeoSD, I have been unable to get this glitch to happen after hours of trying. But I do remember this happening in the past in both games.

If it comes down to it, I'll somehow rig up something to allow me to measure the voltage on the cartridge pin while a game is playing, but I really want to avoid that as I think that will be a huge pain.

## Building real KOF94TE carts

And just a warning if anyone out there wants to try making a real KOF94TE cart (people here and there have talked about this). This wait cycle issue will almost certainly be a problem on real carts. I *think* you can force the pin to ground as a workaround, but that's just a guess.

**Comment by paulb-nl** [comment]
I did some digging and compared the vram writes of kof94 cart and the Neo Geo CD version. Since the CD version does not use wait cycles I expected a difference and I found it.

The cart version uses the instruction `move.w D0, (A1)` to clear parts of vram. This only takes 8 CPU cycles which is not enough without wait cycles. The CD version uses `move.w D0, ($2,A1)` which takes 12 CPU cycles.

I changed the instruction to `move.w (A5), (A1)`. This opcode is still only 1 word and takes 12 CPU cycles.  A5 contains $108000 which is cleared by the System ROM and the game but I don't know if that memory location is used somewhere else in the game. This is just a test to write $0000 to vram in another way to see if it avoids the glitches.

The change is $8032 to $9532 at $133904-133A03 and $133A32-133B31 in the original 055-p1.p1 file.

I did not see any glitches including the win quotes after this change without wait cycles enabled but I just briefly tested this.

This does make the clearing of vram slower when wait cycles are enabled so there is a chance there could be some issues to have this change and wait cycles together if it does not finish in time.

**Comment by city41** [comment]
Nice, this is really interesting. It's especially interesting to hear the cd version doesn't use wait cycles.

The hack was made compatible with wait cycles and so I don't think anything is urgent here. But wait cycles do cause slow down in the game. This is true for the hack and regular kof94. The simplest example is have player 1 ABC charge while player 2 repeatedly jumps in Brazil. 

Fixing kof94 to not need wait cycles and thus fix that slow down would be nice.

> The CD version uses move.w D0, ($2,A1)

Is `move.w D0, ($0, A1)` also 12 cpu cycles? A silly instruction, and an assembler would optimize it out normally. But if it is 12 cycles, maybe it can be used in this situation?

It sounds like if we find a reliable way to write a zero to vram in 12 versus 8 cycles it could be a simple fix.

**Comment by city41** [comment]
Ah I see, `move.w ($0, A1)` works, except it's two words. The CD version must have gotten this part of the game more thoroughly rewritten.

A5 is always `108000`, this is set during vblank and the game never changes it. So I think that can be relied on.

Here is the code in that area

```
0338E0: D06D 103C add.w   ($103c,A5), D0
0338E4: 0640 8200 addi.w  #-$7e00, D0
0338E8: 32C0      move.w  D0, (A1)+
0338EA: 7000      moveq   #$0, D0
0338EC: 322D 1048 move.w  ($1048,A5), D1
0338F0: 5241      addq.w  #1, D1
0338F2: 343C 0080 move.w  #$80, D2
0338F6: 9441      sub.w   D1, D2
0338F8: D442      add.w   D2, D2
0338FA: 41FA 0008 lea     ($8,PC) ; ($33904), A0
0338FE: 4E71      nop
033900: D0C2      adda.w  D2, A0
033902: 4ED0      jmp     (A0)
033904: 3280      move.w  D0, (A1)
033906: 3280      move.w  D0, (A1)
033908: 3280      move.w  D0, (A1)
03390A: 3280      move.w  D0, (A1)
03390C: 3280      move.w  D0, (A1)
03390E: 3280      move.w  D0, (A1)
 ...
```

There is a `moveq` and a `nop`. So I think it would be possible to take those two words and form `move.w #0, (A5)`, which is a two word instruction. Then I think your idea would work?

**Comment by paulb-nl** [comment]
> Nice, this is really interesting. It's especially interesting to hear the cd version doesn't use wait cycles.

AFAIK it is not possible to enable wait cycles on Neo Geo CD

I think `clr.w (A5)` is also a 1 word instruction so it can replace `moveq #$0, D0`.

**Comment by city41** [comment]
I think what I'll do is just go ahead and make this patch, and mark it as experimental. Then use it for a while and see if the game ever has any issues. I can't think of a reliable way to confirm the game never uses 108000 other than that.

**Comment by city41** [comment]
I have made the patch and placed it here

https://neorh-git-kof94-wait-cycles-matt-greers-projects.vercel.app/kof94

This is just a temporary version of my rom hack site, so people won't stumble upon it.

![image](https://github.com/city41/kof94te/assets/141159/193bfc98-4a7b-4b8f-a77b-dfa89e3f5eb3)

You can either apply the patch to vanilla kof94 or pick kof94te to go along with it.

I'll share this with people who helped me test kof94te and see if they'll try it out.

So far I've yet to find a problem with the patch and it does seem to fix the slowdown and graphical glitches. This is really awesome!

@paulb-nl if this patch does go mainstream, let me know how you'd like to be credited on my site. I have your username listed as the creator.

**Comment by city41** [comment]
Oh and I forgot to mention, if you don't pick the Fix Slowdown patch, it sets the ngh to 55 when building a .neo. If you do pick the patch, it sets it to 777.

**Comment by paulb-nl** [comment]
> if this patch does go mainstream, let me know how you'd like to be credited on my site. I have your username listed as the creator.

That's fine.

I think I found another way to do this without using $108000:  `and.w D0, (A1)` is also a 1 word 12 cycle instruction.

**Comment by city41** [comment]
ooh I like that. That should make the patch pretty safe. I'll make that change and then share this with some people.

Thanks, this is a great improvement to this game.

**Comment by city41** [comment]
Ok I have updated the patch to use `and`, and pushed it out to that site. `and` also fixes the issue and I saw no issues in initial testing.

 I've also made an announcement about it on the discord and neo-geo.com's forums in hopes others will give it a try.

I will sit down at some point this weekend and really give this a thorough testing. But I  don't anticipate any problems, I'm pretty optimistic about this patch.

**Comment by city41** [comment]
I think I'm going to go ahead and put this patch on the main site, unless you have any objections, @paulb-nl.

Today I played the game for several hours and never saw the graphical glitch. That's not conclusive unfortunately. But normally after playing that long the glitch would happen at least once.

**Comment by city41** [comment]
btw @paulb-nl I burnt the hack onto eproms and soldered them into a real kof94 cart

![image](https://github.com/user-attachments/assets/8319a306-58c1-4c42-bb90-209b33dd359f)

There is still one part of the hack that has slow down problems due to wait cycles: when p2 presses start while p1 is on the character select screen. the HERE COMES CHALLENGER graphic stays up too long due to the slowdown. It's not a big deal, and the entire rest of the hack works fine, so I left it. Fixing that would have been really hard.

Anyway, this real cart and the mister both behave identical in this scenario. Thought you might find that interesting.

**Comment by paulb-nl** [comment]
Thanks for letting me know. Great to hear that the Mister and real cart have the same behavior.
