### ISSUE TITLE
hold D while starting a game to allow clone characters

### ISSUE THREAD

**Issue by city41** [city41/kof94te#3]
The game engine happily works with clone characters (ie a team of three Kyos for example). If the player holds D will starting a game, allow clone characters by allowing them to pick the same character more than once.

**Comment by ibaraent** [comment]
Could you not do this in the Final Game? It's not how it works on the other KOF's + It will be annoying if this gets added to something and like Fightcade, and then you can do nothing when your opponent picks 3 Heiderns.

**Comment by city41** [comment]
I now know there are other problems clones cause too. I'll just not do this.
